import { HOBBIES } from 'constants';
const {INVESTING, LANDSCAPES, MINIMALISM, MUSIC, ORCHESTRATION, STATISTICS} = HOBBIES;

export default {
  currentHobby: ORCHESTRATION,
  hobbies: [MUSIC, INVESTING, MINIMALISM, STATISTICS, LANDSCAPES]
};
